const stage = (id, title, subtitle, focus, lessons, cover) => ({
  id,
  title,
  subtitle,
  focus,
  cover,
  lessons: lessons.map((item) => {
    const [no, name, slug, kind = "主课"] = item.split("|");
    return { no, name, slug, kind };
  }),
});

const coreCover = "./assets/course-covers/core-path.png";
const dlcCover = "./assets/course-covers/dlc-studies.png";
const materialCover = "./assets/course-covers/materials-technique.png";
const stageFeature = "./assets/course-stage-features";

const COURSE_GROUPS = [
  {
    id: "core",
    eyebrow: "01 / 03",
    title: "四阶段油画主课",
    english: "Four-Stage Oil Painting Path",
    intro: "从看见、判断到表达，把油画学习拆成一条可以反复练习、逐层升级的主线。",
    promise: "先建立观察与造型，再进入光色、画层、艺术史与个人创作。",
    cover: coreCover,
    stages: [
      stage("stage-01", "第一阶段｜基础篇", "观察、明度、形体与写生", "建立油画学习的共同语言：明度、色相、纯度、形体、空间、写生与画面完成度。", [
        "00|色彩之外|course-book-stage-01/lesson-00-vip-beyond-color|序章",
        "01|油画明度详解|course-book-stage-01/lesson-01-main-oil-value",
        "01-1|抽象的明度|course-book-stage-01/lesson-01-01-abstract-value|进阶",
        "01-2|白色（噪音）与色彩（两极）|course-book-stage-01/lesson-01-02-white-noise-color-poles|进阶",
        "01-3|关于绘画的流畅度|course-book-stage-01/lesson-01-03-painting-fluency|补充",
        "02|明度应用：基础形体的认知|course-book-stage-01/lesson-02-main-basic-forms-value",
        "02-1|有色彩属性的色阶及应用|course-book-stage-01/lesson-02-01-colored-value-scales|进阶",
        "03|明度应用：硬与柔、曲面形体的塑造|course-book-stage-01/lesson-03-main-hard-soft-curved-forms",
        "03-1|硬与柔的转换|course-book-stage-01/lesson-03-01-hard-soft-transition|进阶",
        "04|关于油画中的色相|course-book-stage-01/lesson-04-main-oil-hue",
        "05|油画纯度详解|course-book-stage-01/lesson-05-main-oil-chroma",
        "05-1|画面整体色调控制|course-book-stage-01/lesson-05-01-overall-color-tone|进阶",
        "06|色相与纯度的应用|course-book-stage-01/lesson-06-main-hue-chroma-application",
        "06-1|同类限色练习详解（上）|course-book-stage-01/lesson-06-01-limited-palette-up|进阶",
        "06-2|同类限色练习详解（下）|course-book-stage-01/lesson-06-02-limited-palette-down|进阶",
        "07|固有色、光源色与环境色|course-book-stage-01/lesson-07-inherent-light-environment-color",
        "08|光与色的应用|course-book-stage-01/lesson-08-light-color-application",
        "09|图像的选择：油画中的传移摹写|course-book-stage-01/lesson-09-image-selection-transfer-copying",
        "09-1|静物临摹演示：铺色与衔接（上）|course-book-stage-01/lesson-09-01-still-life-copying-up|示范",
        "09-2|静物临摹演示：铺色与衔接（下）|course-book-stage-01/lesson-09-02-still-life-copying-down|示范",
        "09-3|如何定义一张作品的完成（上）|course-book-stage-01/lesson-09-03-defining-completion-up|进阶",
        "09-4|如何定义一张作品的完成（下）|course-book-stage-01/lesson-09-04-defining-completion-down|进阶",
        "10|写生与表现（上）|course-book-stage-01/lesson-10-01-plein-air-expression-up",
        "10-2|写生与表现（下）：第一阶段总结|course-book-stage-01/lesson-10-02-plein-air-expression-down-summary",
        "11|关于写生的一切（上）|course-book-stage-01/lesson-11-01-all-about-plein-air-up",
        "11-2|关于写生的一切（下）|course-book-stage-01/lesson-11-02-all-about-plein-air-down",
        "12-1|写生示范：起稿与画面暗部|course-book-stage-01/lesson-12-01-plein-air-demo-up-dark-block-in|示范",
        "12-2|写生示范：中间色调的衔接|course-book-stage-01/lesson-12-02-plein-air-demo-middle-midtones|示范",
        "12-3|写生示范：亮部塑造与画面调整|course-book-stage-01/lesson-12-03-plein-air-demo-down-lights-adjustment|示范",
      ], `${stageFeature}/stage-01-foundations.png`),
      stage("stage-02", "第二阶段｜印象篇", "光色、直接画法与艺术家研究", "从马奈、莫奈、毕沙罗、修拉、梵高到塞尚，理解光色如何改变画面组织，并把研究转化为可操作的练习。", [
        "01|油画的起点|course-book-stage-02/lesson-01-oil-painting-start",
        "02|马奈的绘画与明度控制|course-book-stage-02/lesson-02-manet-value-control",
        "03-1|马奈临摹：整体色彩预设与画面控制（上）|course-book-stage-02/lesson-03-01-manet-copying-color-preset-up|示范",
        "03-2|马奈临摹：整体色彩预设与画面控制（下）|course-book-stage-02/lesson-03-02-manet-copying-color-preset-down|示范",
        "03-4|直接画法中白色的使用（一）|course-book-stage-02/lesson-03-04-direct-painting-white-use-01|进阶",
        "03-5|直接画法中白色的使用（二）|course-book-stage-02/lesson-03-05-direct-painting-white-use-02|进阶",
        "03-6|直接画法中白色的使用（三）|course-book-stage-02/lesson-03-06-direct-painting-white-use-03|进阶",
        "03-7|直接画法中白色的使用（四）|course-book-stage-02/lesson-03-07-direct-painting-white-use-04|进阶",
        "04|莫奈的光与色|course-book-stage-02/lesson-04-monet-light-and-color",
        "04-1|毕沙罗的艺术之路：自我迭代与风格养成|course-book-stage-02/lesson-04-01-pissarro-artistic-path|进阶",
        "04-2|画面收紧与放松的控制（一）|course-book-stage-02/lesson-04-02-pissarro-tight-loose-control|进阶",
        "04-3|画面收紧与放松的控制（二）|course-book-stage-02/lesson-04-03-pissarro-tight-loose-control-02|进阶",
        "04-4|写生与临摹的应用（三）|course-book-stage-02/lesson-04-04-pissarro-plein-air-copying-application-03|示范",
        "04-5|写生与临摹的应用（四）|course-book-stage-02/lesson-04-05-pissarro-plein-air-copying-application-04|示范",
        "04-6|写生与临摹的应用（五）|course-book-stage-02/lesson-04-06-pissarro-plein-air-copying-application-05|示范",
        "04-7|写生与临摹的应用（六）|course-book-stage-02/lesson-04-07-pissarro-plein-air-copying-application-06|示范",
        "05|莫奈的光色实验|course-book-stage-02/lesson-05-monet-light-color-experiment",
        "06|印象派的理性之光：修拉的艺术研究|course-book-stage-02/lesson-06-seurat-art-research",
        "07-1|修拉的点彩应用（上）|course-book-stage-02/lesson-07-01-seurat-pointillism-application-up|示范",
        "07-2|修拉的点彩应用（下）|course-book-stage-02/lesson-07-02-seurat-pointillism-application-down|示范",
        "08|点彩的继承与发展：保罗·西涅克|course-book-stage-02/lesson-08-signac-pointillism-development",
        "09-1|点彩中的局部推衍与整体布局|course-book-stage-02/lesson-09-01-pointillism-local-evolution-layout|示范",
        "09-2|点彩中的底色与上层色彩转换|course-book-stage-02/lesson-09-02-pointillism-ground-upper-color-transition|示范",
        "10|情绪的力量：梵高的艺术追求|course-book-stage-02/lesson-10-van-gogh-emotional-force",
        "10-1|萨金特的绘画艺术：不能被定义的流派|course-book-stage-02/lesson-10-01-sargent-undefinable-art|进阶",
        "10-2|直接画法静物写生演示（上）|course-book-stage-02/lesson-10-02-direct-painting-still-life-demo-up|示范",
        "10-3|直接画法静物写生演示（下）|course-book-stage-02/lesson-10-03-direct-painting-still-life-demo-down|示范",
        "11|梵高绘画中的技法分析及应用|course-book-stage-02/lesson-11-van-gogh-technique-analysis-application",
        "12|塞尚与新世代的“真实”|course-book-stage-02/lesson-12-cezanne-new-generation-reality",
        "12-1|后印象之后：纳比派之眼|course-book-stage-02/lesson-12-01-after-impressionism-nabi-eye|进阶",
        "12-2|有关生活场景的创作（一）|course-book-stage-02/lesson-12-02-life-scene-creation-01|示范",
        "12-3|有关生活场景的创作（二）|course-book-stage-02/lesson-12-03-life-scene-creation-02|示范",
        "12-4|有关生活场景的创作（三）|course-book-stage-02/lesson-12-04-life-scene-creation-03|示范",
        "12-5|有关生活场景的创作（四）|course-book-stage-02/lesson-12-05-life-scene-creation-04|示范",
      ], `${stageFeature}/stage-02-impressionism.png`),
      stage("stage-03", "第三阶段｜古典篇", "大师、画层与材料实验", "从德拉克洛瓦、戈雅、弗里德里希、透纳到库尔贝、米勒、柯罗与古典大师，建立画层、构图和材料意识。", [
        "01|光影对固有色的影响：从德拉克洛瓦的画中学什么|course-book-stage-03/lesson-01-delacroix-light-local-color",
        "01-1|光影与固有色的绘制：德拉克洛瓦技法演示|course-book-stage-03/lesson-02-delacroix-light-local-colour-demo|示范",
        "01-2|整体规划与底色光影|course-book-stage-03/lesson-03-overall-planning-ground-light|示范",
        "02|画层分解：从戈雅看艺术之变革|course-book-stage-03/lesson-04-goya-layer-analysis",
        "02-1|画层次序的判断和绘制（一）|course-book-stage-03/lesson-05-goya-layer-sequence-demo-1|示范",
        "02-2|画层次序的判断和绘制（二）|course-book-stage-03/lesson-06-goya-layer-sequence-demo-2|示范",
        "03|弗里德里希与浪漫主义绘画|course-book-stage-03/lesson-07-friedrich-romanticism",
        "03-1|弗里德里希的构图美学及技法应用（一）|course-book-stage-03/lesson-08-friedrich-composition-technique-1|示范",
        "03-2|弗里德里希的构图美学及技法应用（二）|course-book-stage-03/lesson-09-friedrich-composition-technique-2|示范",
        "04|关于透纳的绘画|course-book-stage-03/lesson-10-turner-painting",
        "04-1|透纳：哑光丙烯与材料实验|course-book-stage-03/lesson-11-turner-matte-acrylic-material-experiment|示范",
        "04-2|透纳：油画与底层的结合|course-book-stage-03/lesson-12-turner-oil-acrylic-layer-integration|示范",
        "05|库尔贝与现实主义|course-book-stage-03/lesson-13-courbet-realism",
        "05-1|关于库尔贝的《画室》|course-book-stage-03/lesson-14-courbet-the-artists-studio|研究",
        "06|米勒、巴比松画派与现实主义|course-book-stage-03/lesson-15-millet-barbizon-realism",
        "07|柯罗的技艺：摆脱模仿，深入自然（一）|course-book-stage-03/lesson-16-corot-nature-1",
        "14|《马拉之死》的绘画技巧：新古典主义|course-book-stage-03/lesson-17-death-of-marat-neoclassicism|研究",
        "18|传承与多元：弗拉格纳尔|course-book-stage-03/lesson-18-fragonard-inheritance-diversity|研究",
        "19|朴实与亲切：夏尔丹的静物画|course-book-stage-03/lesson-19-chardin-still-life|研究",
        "20|艳丽与油腻：布歇的洛可可精神|course-book-stage-03/lesson-20-boucher-rococo|研究",
        "21-1|《读书的女孩儿》临摹示范（上）|course-book-stage-03/lesson-21-young-girl-reading-demo-1|示范",
        "21-2|《读书的女孩儿》临摹示范（下）|course-book-stage-03/lesson-22-young-girl-reading-demo-2|示范",
        "23|优雅与命运：勒布伦|course-book-stage-03/lesson-23-vigee-le-brun-grace-destiny|研究",
      ], `${stageFeature}/stage-03-classical.png`),
      stage("stage-04", "第四阶段｜创作篇", "从临摹方法到个人系列", "把前面建立的观察、画层、光色与艺术家研究，转化为个人创作、主题选择和持续完成作品的能力。", [
        "S1E01|创作的力量|course-book-stage-04/lesson-01-s1e01-creative-power",
        "S1E02|伦勃朗的自画像|course-book-stage-04/lesson-02-s1e02-rembrandt-self-portrait",
        "S1E03-1|伦勃朗自画像临摹：暗部与灰色层|course-book-stage-04/lesson-03-s1e03-01-dark-and-gray|示范",
        "S1E03-2|伦勃朗自画像临摹：受光面的塑造|course-book-stage-04/lesson-04-s1e03-02-light-modeling|示范",
        "S1E03-3|伦勃朗自画像临摹：初步罩染|course-book-stage-04/lesson-05-s1e03-03-first-glaze|示范",
        "S1E03-4|伦勃朗自画像临摹：灰色层与二次染色|course-book-stage-04/lesson-06-s1e03-04-gray-second-color|示范",
        "S1E03-5|伦勃朗自画像临摹：最终调整|course-book-stage-04/lesson-07-s1e03-05-final-adjustment|示范",
        "S1E04-1|《幽灵公主》：画底与初步塑造|course-book-stage-04/lesson-08-s1e04-01-ground-first-modeling|示范",
        "S1E04-2|《幽灵公主》：绘画痕迹与死灰色层|course-book-stage-04/lesson-09-s1e04-02-marks-dead-color|示范",
        "S1E04-3|《幽灵公主》：暗部到色彩平衡|course-book-stage-04/lesson-10-s1e04-03-dark-color-balance|示范",
        "S1E04-4|《幽灵公主》：初层罩染|course-book-stage-04/lesson-11-s1e04-04-first-glaze|示范",
        "S1E04-5|《幽灵公主》：多层罩染与最终调整|course-book-stage-04/lesson-12-s1e04-05-layered-glaze-final|示范",
        "S2E01-1|关于鲁本斯的群像绘制|course-book-stage-04/lesson-13-s2e01-01-rubens-group-figures",
        "S2E01-2|宗教、神话、肖像、风景：鲁本斯的创作主题|course-book-stage-04/lesson-14-s2e01-02-rubens-themes",
        "S2E02-1|《狮子洞中的但以理》：定稿、起稿与底色|course-book-stage-04/lesson-15-s2e02-01-transfer-ground|示范",
        "S2E02-2|《狮子洞中的但以理》：底色肌理与褐色底|course-book-stage-04/lesson-16-s2e02-02-brown-ground-texture|示范",
        "S2E02-3|《狮子洞中的但以理》：暗部色彩控制|course-book-stage-04/lesson-17-s2e02-03-dark-color-control|示范",
        "S2E02-4|《狮子洞中的但以理》：局部罩染与深入刻画（上）|course-book-stage-04/lesson-18-s2e02-04-local-glaze|示范",
        "S2E02-5|《狮子洞中的但以理》：局部罩染与深入刻画（下）|course-book-stage-04/lesson-19-s2e02-05-local-glaze|示范",
      ], `${stageFeature}/stage-04-creation.png`),
    ],
  },
  {
    id: "dlc",
    eyebrow: "02 / 03",
    title: "DLC 专题课",
    english: "DLC / Special Studies",
    intro: "把主线中反复出现、但值得单独拆开的关键问题，做成可以插入学习路线的专题模块。",
    promise: "适合补短板、做专项练习，或在进入更复杂创作前补齐方法。",
    cover: dlcCover,
    stages: [stage("dlc-all", "DLC｜专项补充", "素描、色彩、风景、肌理与罩染", "DLC 不替代四阶段主课，而是为主线提供可插入的专项训练和材料实验。", [
      "01|素描的底层逻辑|course-book-dlc/lesson-01-sketch-logic|专题",
      "02|色彩范围的确认与进阶色环|course-book-dlc/lesson-02-color-range-wheel|专题",
      "03|画风景是在画什么？|course-book-dlc/lesson-03-landscape-question|专题",
      "04|绘画的肌理|course-book-dlc/lesson-04-painting-texture|专题",
      "05|高效发挥油画特性：以坦培拉为基底|course-book-dlc/lesson-05-tempera-base-oil|专题",
      "06|罩染前的底稿建设及简易拓印|course-book-dlc/lesson-06-ground-transfer-before-glazing|专题",
      "07|罩染：局部色调调整（一）|course-book-dlc/lesson-07-glazing-local-adjustment-1|专题",
      "08|罩染：局部色调调整（二）|course-book-dlc/lesson-08-glazing-local-adjustment-2|专题",
    ], `${stageFeature}/dlc-special-studies.png`)],
  },
  {
    id: "materials",
    eyebrow: "03 / 03",
    title: "材料与技法",
    english: "Materials & Technique",
    intro: "从颜料、工具、研磨到色系测试与干燥观察，把“材料选择”变成可验证的工作方法。",
    promise: "适合准备购买材料、想摆脱盲目试错，或希望建立自己的颜料与媒介数据库的学习者。",
    cover: materialCover,
    stages: [stage("materials-all", "材料与技法｜全目录", "工具、颜料家族与专业边界", "先认识材料，再观察材料在画面中的行为：覆盖、染色、干燥、透明、混合与层间关系。", [
      "01|油画颜料概述|course-book-material-technique/lesson-01-oil-paint-overview|基础",
      "02|油画颜料的品牌与标签|course-book-material-technique/lesson-02-brands-and-labels|基础",
      "03|油画颜料的级别与染色能力|course-book-material-technique/lesson-03-grades-and-staining|基础",
      "04|调色板|course-book-material-technique/lesson-04-palette|工具",
      "05|油壶|course-book-material-technique/lesson-05-oil-pot|工具",
      "06|画刀|course-book-material-technique/lesson-06-painting-knife|工具",
      "07|画笔（一）|course-book-material-technique/lesson-07-brushes-1|工具",
      "08|画笔（二）|course-book-material-technique/lesson-08-brushes-2|工具",
      "09|画笔（三）|course-book-material-technique/lesson-09-brushes-3|工具",
      "10|画架与画箱|course-book-material-technique/lesson-10-easel-and-paint-box|工具",
      "11|颜料研磨（上）|course-book-material-technique/lesson-11-grinding-1|专业边界",
      "12|颜料研磨（下）|course-book-material-technique/lesson-12-grinding-2|专业边界",
      "13|黄色系（一）：画布准备、国产颜料对比与色相概述|course-book-material-technique/lesson-13-yellow-1|黄色系",
      "14|黄色系（二）：色相名称、铬黄与镍钛黄|course-book-material-technique/lesson-14-yellow-2|黄色系",
      "15|黄色系（三）：拿浦黄、镉黄、印度黄与干燥测试|course-book-material-technique/lesson-15-yellow-3|黄色系",
      "16|黄色系（四）：老颜料、钴黄与干燥后对比|course-book-material-technique/lesson-16-yellow-4|黄色系",
      "17|红色系前言|course-book-material-technique/lesson-17-red-preface|红色系",
      "18|镉红|course-book-material-technique/lesson-18-cadmium-red|红色系",
      "19|茜红|course-book-material-technique/lesson-19-alizarin-red|红色系",
      "20|混合红|course-book-material-technique/lesson-20-mixed-red|红色系",
      "21|朱红|course-book-material-technique/lesson-21-vermilion-red|红色系",
      "22|群青|course-book-material-technique/lesson-22-ultramarine|蓝色系",
      "23|普鲁士蓝|course-book-material-technique/lesson-23-prussian-blue|蓝色系",
      "24|钴蓝|course-book-material-technique/lesson-24-cobalt-blue|蓝色系",
      "25|天蓝|course-book-material-technique/lesson-25-cerulean-blue|蓝色系",
      "26|酞菁蓝|course-book-material-technique/lesson-26-phthalo-blue|蓝色系",
      "27|绿色系|course-book-material-technique/lesson-27-green-family|绿色系",
      "28|一张图了解油画的黑色|course-book-material-technique/lesson-28-black-overview|黑色系",
      "29|最黑的黑|course-book-material-technique/lesson-29-blackest-black|黑色系",
      "30|土黄、黄赭与赭石：PY43/PY42|course-book-material-technique/lesson-30-earth-yellow-ochres|土棕色系",
      "31|PBr7：生褐与熟褐|course-book-material-technique/lesson-31-umbers|土棕色系",
      "32|PBr6：干燥、结膜与古典绘画应用|course-book-material-technique/lesson-32-pbr6-drying|土棕色系",
      "33|混合棕色、凡戴克棕与材料故事|course-book-material-technique/lesson-33-mixed-browns-vandyke|土棕色系",
      "34|PR101/PR102：氧化铁红的故事|course-book-material-technique/lesson-34-iron-oxide-reds|土棕色系",
    ], `${stageFeature}/materials-technique.png`)],
  },
];

window.COURSE_GROUPS = COURSE_GROUPS;
