window.WORKSHOP_UPDATES = [
  {
    "date": "2026-07-11",
    "type": "视频",
    "title": "这门五天课真正解决什么",
    "time": "18:30",
    "summary": "重新解释课程定位：它不是软件体验，而是一次真实的作品转译与交付。",
    "cover": "./assets/workshop-hero-v2.png",
    "published": false,
    "url": "",
    "status": "planned"
  },
  {
    "date": "2026-07-12",
    "type": "直播",
    "title": "两类学员如何在五天完成一套作品",
    "time": "20:00",
    "summary": "重新解释课程定位：它不是软件体验，而是一次真实的作品转译与交付。",
    "cover": "./assets/workshop-modeling.png",
    "published": false,
    "url": "",
    "status": "planned"
  },
  {
    "date": "2026-07-13",
    "type": "图文",
    "title": "不是重新打造 IP，而是让已有内容进入现实",
    "time": "11:30",
    "summary": "用课程示范和具体判断，说明已有作品与只有想法的人如何进入同一条生产路线。",
    "cover": "./assets/workshop-modeling.png",
    "published": false,
    "url": "",
    "status": "planned"
  },
  {
    "date": "2026-07-14",
    "type": "视频",
    "title": "一张图怎样一步步变成三维模型",
    "time": "19:30",
    "summary": "用课程示范和具体判断，说明已有作品与只有想法的人如何进入同一条生产路线。",
    "cover": "./assets/workshop-printing-v2.png",
    "published": false,
    "url": "",
    "status": "planned"
  },
  {
    "date": "2026-07-15",
    "type": "图文",
    "title": "一张角色图进入三维前，要补齐哪些信息",
    "time": "11:30",
    "summary": "从正侧背、遮挡、重心和结构厚度四个具体问题，说明二维作品进入三维前的结构转译。",
    "cover": "./assets/updates/2026-07-15/workshop-modeling.png",
    "published": true,
    "url": "./updates/2026-07-15-character-image-to-3d-input.html",
    "status": "published"
  },
  {
    "date": "2026-07-16",
    "type": "图文",
    "title": "没有成熟原画，可以从这四项输入开始",
    "time": "11:30",
    "summary": "用故事、关键词、参考图和使用场景建立第一版项目输入，再进入视觉、三维和实体制作。",
    "cover": "./assets/updates/2026-07-16/workshop-hero-v2.png",
    "published": true,
    "url": "./updates/2026-07-16-start-with-four-inputs.html",
    "status": "published"
  },
  {
    "date": "2026-07-17",
    "type": "视频",
    "title": "AI 初模为什么不能直接拿去打印",
    "time": "19:30",
    "summary": "AI 初模先解决形象与体块方向，进入打印前仍要检查封闭性、厚度、连接、重心和部件关系，并通过人工修模形成可打印文件。",
    "cover": "./assets/updates/2026-07-17/01-website-hero.png",
    "published": true,
    "url": "./updates/2026-07-17-why-ai-draft-cannot-print-directly.html",
    "status": "published"
  },
  {
    "date": "2026-07-18",
    "type": "视频",
    "title": "开放工作室会看到的 7 样真实东西",
    "time": "18:00",
    "summary": "用七类可核验的资料、文件、设备、样件与工具，检查一门 IP 实物化课程是否覆盖从视觉输入到实体和发布的完整链路。",
    "cover": "./assets/updates/2026-07-18/01-website-hero.png",
    "published": true,
    "url": "./updates/2026-07-18-seven-things-in-an-open-workshop.html",
    "status": "published"
  },
  {
    "date": "2026-07-19",
    "type": "直播",
    "title": "公开拆解：现场判断一件作品适合做什么",
    "time": "20:00",
    "summary": "用用途、轮廓、受力、细节尺度、工艺与时间边界，先判断一件作品更适合完整立体、半身/局部、浮雕或其他降级出口，再决定是否进入三维制作。",
    "cover": "./assets/updates/2026-07-19/01-website-hero.png",
    "published": true,
    "url": "./updates/2026-07-19-decide-what-a-work-should-become.html",
    "status": "published"
  },
  {
    "date": "2026-07-20",
    "type": "图文",
    "title": "报名之后，你会收到什么",
    "time": "11:30",
    "summary": "把报名提交、人工确认、课前准备、五天课程交付与课后延续分开说明，让不同起点的参与者知道每个节点会形成什么资料、文件、样件与下一步。",
    "cover": "./assets/updates/2026-07-20/01-website-hero.png",
    "published": true,
    "url": "./updates/2026-07-20-what-you-receive-after-applying.html",
    "status": "published"
  },
  {
    "date": "2026-07-21",
    "type": "图文",
    "title": "已有 IP 学员，课前请准备这 6 类资料",
    "time": "11:30",
    "summary": "把已有 IP 的原始作品、角色设定、结构视图、材质参考、实体目标与版权边界整理成六类可核验资料，让 Day 1 能直接判断范围并建立主、备、降级方案。",
    "cover": "./assets/updates/2026-07-21/01-website-hero.png",
    "published": true,
    "url": "./updates/2026-07-21-six-pre-course-materials-for-existing-ip.html",
    "status": "published"
  },
  {
    "date": "2026-07-22",
    "type": "视频",
    "title": "没有成熟 IP，怎样从关键词做出第一版主视觉",
    "time": "19:30",
    "summary": "把抽象关键词改写成用途、轮廓、姿态、材质与色彩等可见约束，先形成可比较的主视觉方向，再为三维结构补齐后续输入。",
    "cover": "./assets/updates/2026-07-22/01-website-hero.png",
    "published": true,
    "url": "./updates/2026-07-22-turn-keywords-into-first-key-visual.html",
    "status": "published"
  },
  {
    "date": "2026-07-23",
    "type": "图文",
    "title": "五天结束，你至少带走这 10 项成果",
    "time": "11:30",
    "summary": "把五天成果按判断资料、数字文件、实体验证、产品表达和持续发布五组说明，并明确每项用途、相互依赖关系与基础、标准、进阶完成度边界。",
    "cover": "./assets/updates/2026-07-23/01-website-hero.png",
    "published": true,
    "url": "./updates/2026-07-23-ten-outcomes-after-five-days.html",
    "status": "published"
  },
  {
    "date": "2026-07-24",
    "type": "视频",
    "title": "GLB 和 STL，不只是两个文件后缀",
    "time": "19:30",
    "summary": "区分 GLB 的在线展示用途与 STL 的切片制造用途，并用用途、内容、结构、验证和版本五项标准检查双文件交付。",
    "cover": "./assets/updates/2026-07-24/01-website-hero.png",
    "published": true,
    "url": "./updates/2026-07-24-glb-and-stl-are-more-than-file-extensions.html",
    "status": "published"
  },
  {
    "date": "2026-07-25",
    "type": "视频",
    "title": "为什么五天课建议把作品控制在 8-12cm",
    "time": "18:00",
    "summary": "把 8-12cm 作为五天首次闭环的建议尺度，用用途、外接尺寸、结构、细节、制造排程和后处理空间判断具体项目是否适合，并保留调整与降级出口。",
    "cover": "./assets/updates/2026-07-25/01-website-hero.png",
    "published": true,
    "url": "./updates/2026-07-25-why-keep-the-work-between-8-and-12cm.html",
    "status": "published"
  },
  {
    "date": "2026-07-26",
    "type": "直播",
    "title": "五天能不能做完：基础、标准、进阶三种出口",
    "time": "20:00",
    "summary": "用范围、Gate 证据与可继续性区分基础、标准、进阶三种完成出口，让不同起点的项目在五天内形成真实、可核验且能继续推进的结果。",
    "cover": "./assets/updates/2026-07-26/01-website-hero.png",
    "published": true,
    "url": "./updates/2026-07-26-three-realistic-outcomes-in-five-days.html",
    "status": "published"
  },
  {
    "date": "2026-07-27",
    "type": "图文",
    "title": "这门课不是软件课，而是一次完整交付",
    "time": "11:30",
    "summary": "用交付对象、验收证据、版本关系和下一阶段可继续性，解释五天课程为何不能被拆成若干软件操作，而要把同一项目从方向判断推进到文件、实体、表达与数字发布。",
    "cover": "./assets/updates/2026-07-27/01-website-hero.png",
    "published": true,
    "url": "./updates/2026-07-27-a-complete-project-handoff-not-a-software-class.html",
    "status": "published"
  },
  {
    "date": "2026-07-28",
    "type": "视频",
    "title": "Nomad 修模，五天里最关键的 4 个动作",
    "time": "19:30",
    "summary": "用比例轮廓、表面关系、薄弱结构和拆件装配四类可检查动作，说明 AI 三维初模怎样经过人工修正进入 Gate 2。",
    "cover": "./assets/updates/2026-07-28/01-website-hero.png",
    "published": true,
    "url": "./updates/2026-07-28-four-critical-nomad-sculpting-actions.html",
    "status": "published"
  },
  {
    "date": "2026-07-29",
    "type": "图文",
    "title": "四个质量闸口，保证项目不一路带病往后走",
    "time": "11:30",
    "summary": "把 Gate 1 至 Gate 4 定义为有证据的停止、复检与放行机制，分别控制范围输入、模型制造、实体验证和发布一致性。",
    "cover": "./assets/updates/2026-07-29/01-website-hero.png",
    "published": true,
    "url": "./updates/2026-07-29-four-quality-gates-stop-problems-from-moving-forward.html",
    "status": "published"
  },
  {
    "date": "2026-07-30",
    "type": "视频",
    "title": "为什么必须小班：打印机和一对一支持的真实产能",
    "time": "19:30",
    "summary": "用完整打印任务、设备与后处理周转、失败重试和关键节点支持解释小班边界；只给出可核算方法，不虚构每日产量或指导时长。",
    "cover": "./assets/updates/2026-07-30/01-website-hero.png",
    "published": true,
    "url": "./updates/2026-07-30-why-small-classes-match-real-printing-and-support-capacity.html",
    "status": "published"
  },
  {
    "date": "2026-07-31",
    "type": "图文",
    "title": "7 月咨询最多的 8 个问题",
    "time": "11:30",
    "summary": "集中回答两类起点、五天交付、AI 与人工修正、GLB / STL、建议尺寸、完成度、小班产能和报名边界。",
    "cover": "./assets/updates/2026-07-31/01-website-hero.jpg",
    "published": true,
    "url": "./updates/2026-07-31-eight-questions-before-applying.html",
    "status": "published"
  },
  {
    "date": "2026-08-01",
    "type": "视频",
    "title": "报名不是付款结束，而是课前项目已经启动",
    "time": "18:00",
    "summary": "把报名提交、人工确认、付款确认与课前项目启动分开说明，并用起点资料、项目卡、版权与范围、设备检查、目录版本和 Gate 1 预检六项记录，为 Day 1 建立可核验输入。",
    "cover": "./assets/updates/2026-08-01/01-website-hero.png",
    "published": true,
    "url": "./updates/2026-08-01-pre-course-project-starts-after-confirmation.html",
    "status": "published"
  },
  {
    "date": "2026-08-02",
    "type": "直播",
    "title": "开放工作室：真实工具、样品和五天流程",
    "time": "20:00",
    "summary": "用同一项目的输入、受控文件、制造设备、阶段样品和发布归档建立可复核观察路径，说明开放工作室应如何证明五天流程关系，而不是只陈列设备。",
    "cover": "./assets/updates/2026-08-02/01-website-hero.png",
    "published": true,
    "url": "./updates/2026-08-02-open-workshop-tools-samples-and-five-day-evidence.html",
    "status": "published"
  },
  {
    "date": "2026-08-03",
    "type": "图文",
    "title": "Day 1 到底做什么：先把方向做对",
    "time": "11:30",
    "summary": "用项目卡、用途与尺寸、结构输入、版权状态和主 / 备 / 降级方案说明 Day 1 如何完成 Gate 1 范围锁定，为 Day 2 留下可复核输入。",
    "cover": "./assets/updates/2026-08-03/01-website-hero.png",
    "published": true,
    "url": "./updates/2026-08-03-day-1-lock-direction-before-making.html",
    "status": "published"
  },
  {
    "date": "2026-08-04",
    "type": "视频",
    "title": "同一门课，两种入口：已有作品和只有想法",
    "time": "19:30",
    "summary": "区分已有 IP / 角色资产与只有想法、草图或初步设定的输入准备方式，并说明两者如何在 Day 1 汇入同一项目卡和 Gate 1 标准。",
    "cover": "./assets/updates/2026-08-04/01-website-hero.png?v=61f682ee8340",
    "published": true,
    "url": "./updates/2026-08-04-two-starting-points-one-gate-1-standard.html",
    "status": "published"
  },
  {
    "date": "2026-08-05",
    "type": "图文",
    "title": "结构转译要判断的，不只是像不像",
    "time": "11:30",
    "summary": "用轮廓、体块、遮挡、真实厚度、重心、分件与材料对应检查二维形象能否进入三维，并说明 Day 1 / Gate 1 如何为 Day 2 留下可复核输入。",
    "cover": "./assets/updates/2026-08-05/01-website-hero.png",
    "published": true,
    "url": "./updates/2026-08-05-structure-translation-is-more-than-likeness.html",
    "status": "published"
  },
  {
    "date": "2026-08-06",
    "type": "视频",
    "title": "AI 视觉输入图，为什么要准备正侧背和材质",
    "time": "19:30",
    "summary": "用正面、侧面、背面和材质四类输入消除轮廓、厚度、遮挡、连接与表面解释的不确定性，并说明 Day 1 / Gate 1 如何形成 Day 2 可复核的受控输入。",
    "cover": "./assets/updates/2026-08-06/01-website-hero.png",
    "published": true,
    "url": "./updates/2026-08-06-why-ai-visual-input-needs-front-side-back-and-materials.html",
    "status": "published"
  },
  {
    "date": "2026-08-07",
    "type": "图文",
    "title": "公开展示前，先把版权状态写清楚",
    "time": "11:30",
    "summary": "用来源、权利主体、授权范围、公开边界和受控版本五类记录检查视觉输入，说明 Day 1 / Gate 1 如何为三维制作与后续发布建立可追溯边界。",
    "cover": "./assets/updates/2026-08-07/01-website-hero.png?v=5c571f4cc40d",
    "published": true,
    "url": "./updates/2026-08-07-clarify-copyright-status-before-public-display.html",
    "status": "published"
  },
  {
    "date": "2026-08-08",
    "type": "视频",
    "title": "从作品筛选到 Gate 1 通过：完整 Day 1 案例",
    "time": "18:00",
    "summary": "用对象与用途、尺寸视图、结构识别点、版权边界、主 / 备 / 降级方案和 Gate 1 放行六项记录，完整说明 Day 1 怎样为 Day 2 留下可复核输入；所有场景均为课程方向示意，不冒充真实案例。",
    "cover": "./assets/updates/2026-08-08/01-website-hero.png",
    "published": true,
    "url": "./updates/2026-08-08-from-work-selection-to-gate-1-day-1-walkthrough.html",
    "status": "published"
  },
  {
    "date": "2026-08-09",
    "type": "直播",
    "title": "Day 1 实战演示：从作品 / 关键词到可做方案",
    "time": "20:00",
    "summary": "用输入盘点、对象收敛、尺寸与结构预判、主 / 备 / 降级方案和 Gate 1 决定，说明已有作品与早期想法如何形成可进入 Day 2 的受控方案；演示内容只作课程方向说明，不冒充真实学员案例。",
    "cover": "./assets/updates/2026-08-09/01-website-hero.png",
    "published": true,
    "url": "./updates/2026-08-09-day-1-demo-from-artwork-or-keywords-to-a-workable-plan.html",
    "status": "published"
  },
  {
    "date": "2026-08-10",
    "type": "图文",
    "title": "Day 2 到底做什么：从初模到双文件输出",
    "time": "11:30",
    "summary": "用初模筛选、受控版本、Nomad 人工修模、拆件装配、GLB / STL 双文件与 Gate 2 检查，说明 Day 2 如何为首轮打印留下可复核交接。",
    "cover": "./assets/updates/2026-08-10/01-website-hero.png",
    "published": true,
    "url": "./updates/2026-08-10-day-2-from-initial-model-to-dual-file-output.html",
    "status": "published"
  },
  {
    "date": "2026-08-11",
    "type": "视频",
    "title": "三维生成失败，通常不是因为你不会用工具",
    "time": "19:30",
    "summary": "用输入层、身份层、结构层和制造层定位三维生成失败，再决定退回输入、重选候选、人工修模或启用降级方案。",
    "cover": "./assets/updates/2026-08-11/01-website-hero.png",
    "published": true,
    "url": "https://chuyiouart.github.io/chuyi/ip-object-workshop/updates/2026-08-11-why-3d-generation-fails-beyond-tool-skills.html",
    "status": "published"
  },
  {
    "date": "2026-08-12",
    "type": "图文",
    "title": "Nomad 基础不是学菜单，而是修四类问题",
    "time": "11:30",
    "summary": "把 Nomad 修模收敛为比例轮廓、表面网格、薄壁悬空、拆件装配四类可定位问题，并以修前标记、单项动作和修后复检完成 Gate 2 交接。",
    "cover": "./assets/updates/2026-08-12/01-website-hero-fallback.png?v=4dbb53c4ca38",
    "published": true,
    "url": "https://chuyiouart.github.io/chuyi/ip-object-workshop/updates/2026-08-12-nomad-basics-fix-four-problem-types.html",
    "status": "published",
    "coverImage": {
      "srcset": "./assets/updates/2026-08-12/01-website-hero-480.webp?v=a052493f8a1d 480w, ./assets/updates/2026-08-12/01-website-hero-768.webp?v=7352f6020b60 768w, ./assets/updates/2026-08-12/01-website-hero-1280.webp?v=5953f072b235 1280w",
      "sizes": "(max-width: 680px) 100vw, 760px",
      "fallback": "./assets/updates/2026-08-12/01-website-hero-fallback.png?v=4dbb53c4ca38",
      "width": 960,
      "height": 540
    }
  },
  {
    "date": "2026-08-13",
    "type": "图文",
    "title": "一个模型怎样通过 Gate 2 可打印检查",
    "time": "11:30",
    "summary": "用受控版本、封闭网格、真实厚度、重心支撑、拆件装配和切片预检六项证据，判断模型能否通过 Gate 2 进入首轮打印。",
    "cover": "./assets/updates/2026-08-13/01-website-hero-fallback.png?v=f76547f70d84",
    "published": true,
    "url": "https://chuyiouart.github.io/chuyi/ip-object-workshop/updates/2026-08-13-how-a-model-passes-gate-2-printability-check.html",
    "status": "published",
    "coverImage": {
      "srcset": "./assets/updates/2026-08-13/01-website-hero-480.webp?v=16b70dc2fe27 480w, ./assets/updates/2026-08-13/01-website-hero-768.webp?v=b4666a6dd0c1 768w, ./assets/updates/2026-08-13/01-website-hero-1280.webp?v=604d3280eb65 1280w",
      "sizes": "(max-width: 680px) 100vw, 760px",
      "fallback": "./assets/updates/2026-08-13/01-website-hero-fallback.png?v=f76547f70d84",
      "width": 960,
      "height": 540
    }
  },
  {
    "date": "2026-08-14",
    "type": "视频",
    "title": "同一件作品如何导出 GLB 和 STL",
    "time": "19:30",
    "summary": "从同一受控主模型建立数字展示与实体制造两条出口，分别读回 GLB 和 STL，并用版本、用途与 Gate 2 证据完成交接。",
    "cover": "./assets/updates/2026-08-14/01-website-hero-fallback.png?v=a7540d267930",
    "published": true,
    "url": "https://chuyiouart.github.io/chuyi/ip-object-workshop/updates/2026-08-14-export-glb-and-stl-from-one-controlled-model.html",
    "status": "published",
    "coverImage": {
      "srcset": "./assets/updates/2026-08-14/01-website-hero-480.webp?v=9024668e5c81 480w, ./assets/updates/2026-08-14/01-website-hero-768.webp?v=92f3f58ac720 768w, ./assets/updates/2026-08-14/01-website-hero-1280.webp?v=88ffae6ad9f7 1280w",
      "sizes": "(max-width: 680px) 100vw, 760px",
      "fallback": "./assets/updates/2026-08-14/01-website-hero-fallback.png?v=a7540d267930",
      "width": 960,
      "height": 540
    }
  },
  {
    "date": "2026-08-15",
    "type": "视频",
    "title": "打印为什么从 Day 2 晚上就要开始",
    "time": "18:00",
    "summary": "解释为什么通过 Gate 2 后要在 Day 2 晚上启动首轮关键打印，用不可压缩的设备时间换取 Day 3 可复核的实体证据，同时保留安全、版本与降级边界。",
    "cover": "./assets/updates/2026-08-15/01-website-hero-fallback.png?v=ac6b76002a44",
    "published": true,
    "url": "https://chuyiouart.github.io/chuyi/ip-object-workshop/updates/2026-08-15-why-printing-starts-on-day-2-evening.html",
    "status": "published",
    "coverImage": {
      "srcset": "./assets/updates/2026-08-15/01-website-hero-480.webp?v=cb0c513f9149 480w, ./assets/updates/2026-08-15/01-website-hero-768.webp?v=91a07063768a 768w, ./assets/updates/2026-08-15/01-website-hero-1280.webp?v=4590fc21bf48 1280w",
      "sizes": "(max-width: 680px) 100vw, 760px",
      "fallback": "./assets/updates/2026-08-15/01-website-hero-fallback.png?v=ac6b76002a44",
      "width": 960,
      "height": 540
    }
  },
  {
    "date": "2026-08-16",
    "type": "直播",
    "title": "AI 初模到可打印模型，现场演示一次",
    "time": "20:00",
    "summary": "用受控输入、候选筛选、人工修模、STL 读回与 Gate 2 证据，说明 AI 初模怎样成为可进入首轮打印的模型，同时保留主 / 备 / 降级与完成度边界。",
    "cover": "./assets/updates/2026-08-16/01-website-hero-fallback.png?v=f0501c874506",
    "published": true,
    "url": "./updates/2026-08-16-live-demo-ai-draft-to-printable-model.html",
    "status": "published",
    "media_status": "partial",
    "passedRoles": [
      "website_hero"
    ],
    "pendingRoles": [
      "core_explanation",
      "real_application",
      "social_promotion"
    ],
    "coverImage": {
      "srcset": "./assets/updates/2026-08-16/01-website-hero-480.webp?v=2246f4fef36d 480w, ./assets/updates/2026-08-16/01-website-hero-768.webp?v=d3d2bee8c298 768w, ./assets/updates/2026-08-16/01-website-hero-1280.webp?v=a996e74bdeff 1280w",
      "sizes": "(max-width: 680px) 100vw, 760px",
      "fallback": "./assets/updates/2026-08-16/01-website-hero-fallback.png?v=f0501c874506",
      "width": 960,
      "height": 540
    },
    "source_id": "workshop:2026-08-16"
  },
  {
    "date": "2026-08-17",
    "type": "图文",
    "title": "Day 3 到底做什么：把 STL 变成真实灰模",
    "time": "11:30",
    "summary": "用切片冻结、首轮打印、灰模检查、问题分类与 Gate 3 记录，说明数字文件怎样形成可测量的实体证据，再决定局部修正、降级或进入色彩测试。",
    "cover": "./assets/updates/2026-08-17/01-website-hero-fallback.png?v=e4b9372bff7a",
    "published": true,
    "url": "./updates/2026-08-17-day-3-turn-stl-into-verifiable-gray-model.html",
    "status": "published",
    "source_id": "workshop:2026-08-17",
    "media_status": "complete",
    "passedRoles": [
      "website_hero",
      "core_explanation",
      "real_application",
      "social_promotion"
    ],
    "pendingRoles": [],
    "coverImage": {
      "srcset": "./assets/updates/2026-08-17/01-website-hero-480.webp?v=b6b7309ace02 480w, ./assets/updates/2026-08-17/01-website-hero-768.webp?v=161b1d76c711 768w, ./assets/updates/2026-08-17/01-website-hero-1280.webp?v=d4cfb2ffac97 1280w",
      "sizes": "(max-width: 680px) 100vw, 760px",
      "fallback": "./assets/updates/2026-08-17/01-website-hero-fallback.png?v=e4b9372bff7a",
      "width": 960,
      "height": 540
    }
  },
  {
    "date": "2026-08-18",
    "type": "视频",
    "title": "支撑、朝向和空心，怎样影响打印结果",
    "time": "19:30",
    "summary": "进入 Day 3：切片、打印、灰模处理、色彩和基础涂装。",
    "cover": "./assets/workshop-printing-v2.png",
    "published": false,
    "url": "",
    "status": "planned"
  },
  {
    "date": "2026-08-19",
    "type": "图文",
    "title": "灰模不是半成品，它已经完成一次结构验证",
    "time": "11:30",
    "summary": "进入 Day 3：切片、打印、灰模处理、色彩和基础涂装。",
    "cover": "./assets/workshop-finishing.png",
    "published": false,
    "url": "",
    "status": "planned"
  },
  {
    "date": "2026-08-20",
    "type": "图文",
    "title": "早决策价今日截止：之后恢复标准价",
    "time": "11:30",
    "summary": "进入 Day 3：切片、打印、灰模处理、色彩和基础涂装。",
    "cover": "./assets/workshop-ai-launch.png",
    "published": false,
    "url": "",
    "status": "planned"
  },
  {
    "date": "2026-08-21",
    "type": "视频",
    "title": "涂装之前，先做好一张配色色板",
    "time": "19:30",
    "summary": "进入 Day 3：切片、打印、灰模处理、色彩和基础涂装。",
    "cover": "./assets/workshop-hero-v2.png",
    "published": false,
    "url": "",
    "status": "planned"
  },
  {
    "date": "2026-08-22",
    "type": "视频",
    "title": "从打印件到可展示灰模：后处理完整过程",
    "time": "18:00",
    "summary": "把取件后的树脂打印件按清洗固化、拆撑、缺陷分级、打磨修补、装配校正和侧光复核推进为可检查、可展示并能进入 Gate 3 判断的灰模。",
    "cover": "./assets/updates/2026-08-22/01-website-hero-fallback.png?v=8eeb0a6b54b2",
    "published": true,
    "url": "./updates/2026-08-22-printed-part-to-display-ready-gray-model-post-processing.html",
    "status": "published",
    "source_id": "workshop:2026-08-22",
    "media_status": "complete",
    "passedRoles": [
      "website_hero",
      "core_explanation",
      "real_application",
      "social_promotion"
    ],
    "pendingRoles": [],
    "coverImage": {
      "srcset": "./assets/updates/2026-08-22/01-website-hero-480.webp?v=08a27f7d4086 480w, ./assets/updates/2026-08-22/01-website-hero-768.webp?v=e09348f905cb 768w, ./assets/updates/2026-08-22/01-website-hero-1280.webp?v=8f472dc75d7d 1280w",
      "sizes": "(max-width: 680px) 100vw, 760px",
      "fallback": "./assets/updates/2026-08-22/01-website-hero-fallback.png?v=8eeb0a6b54b2",
      "width": 960,
      "height": 540
    }
  },
  {
    "date": "2026-08-23",
    "type": "直播",
    "title": "灰模到基础涂装，现场完成一个重点局部",
    "time": "20:00",
    "summary": "用同底材样片、三阶明度、三种涂层层序、曲面遮盖和双光源读回，把灰模上的一个高识别局部验证为可交接 Day 4 的涂装依据。",
    "cover": "./assets/updates/2026-08-23/01-website-hero-fallback.png?v=72ebe60b8439",
    "published": true,
    "url": "./updates/2026-08-23-gray-model-to-basic-paint-validate-one-focal-area.html",
    "status": "published",
    "source_id": "workshop:2026-08-23",
    "media_status": "complete",
    "passedRoles": [
      "website_hero",
      "core_explanation",
      "real_application",
      "social_promotion"
    ],
    "pendingRoles": [],
    "coverImage": {
      "srcset": "./assets/updates/2026-08-23/01-website-hero-480.webp?v=534ce4f9a8a3 480w, ./assets/updates/2026-08-23/01-website-hero-768.webp?v=6e1486ec23c0 768w, ./assets/updates/2026-08-23/01-website-hero-1280.webp?v=bda4543e39f7 1280w",
      "sizes": "(max-width: 680px) 100vw, 760px",
      "fallback": "./assets/updates/2026-08-23/01-website-hero-fallback.png?v=72ebe60b8439",
      "width": 960,
      "height": 540
    }
  },
  {
    "date": "2026-08-24",
    "type": "图文",
    "title": "Day 4 到底做什么：让模型开始成为作品 / 产品",
    "time": "11:30",
    "summary": "把通过实体验证的模型推进为可展示、可说明、可归档的受控版本，并用表面、包装方向、说明卡、拍摄与 Gate 4 一致性检查完成 Day 5 交接。",
    "cover": "./assets/updates/2026-08-24/01-website-hero-fallback.png?v=cb69fd5d7e6e",
    "published": true,
    "url": "./updates/2026-08-24-day-4-turn-a-model-into-a-presentable-documented-work.html",
    "status": "published",
    "source_id": "workshop:2026-08-24",
    "media_status": "complete",
    "passedRoles": [
      "website_hero",
      "core_explanation",
      "real_application",
      "social_promotion"
    ],
    "pendingRoles": [],
    "coverImage": {
      "srcset": "./assets/updates/2026-08-24/01-website-hero-480.webp?v=eefe06ee0688 480w, ./assets/updates/2026-08-24/01-website-hero-768.webp?v=9c9fb4959b2b 768w, ./assets/updates/2026-08-24/01-website-hero-1280.webp?v=1540426f1f12 1280w",
      "sizes": "(max-width: 680px) 100vw, 760px",
      "fallback": "./assets/updates/2026-08-24/01-website-hero-fallback.png?v=cb69fd5d7e6e",
      "width": 960,
      "height": 540
    }
  },
  {
    "date": "2026-08-25",
    "type": "视频",
    "title": "四种包装路线，分别适合什么作品",
    "time": "19:30",
    "summary": "用对象尺寸、突出部件、接触禁区、取放路径、信息容量和完成阶段，判断简易贴纸盒、潮流盒装、挂卡 / 吸塑与精装收藏盒的适用条件。",
    "cover": "./assets/updates/2026-08-25/02-core-explanation-fallback.png?v=a13005bc73f0",
    "published": true,
    "url": "./updates/2026-08-25-four-packaging-routes-for-different-ip-objects.html",
    "status": "published",
    "source_id": "workshop:2026-08-25",
    "media_status": "partial",
    "passedRoles": [
      "core_explanation",
      "real_application",
      "social_promotion"
    ],
    "pendingRoles": [
      "website_hero"
    ],
    "coverImage": {
      "srcset": "./assets/updates/2026-08-25/02-core-explanation-480.webp?v=e05fe4356478 480w, ./assets/updates/2026-08-25/02-core-explanation-768.webp?v=e3d68cc06bab 768w",
      "sizes": "(max-width: 680px) 100vw, 50vw",
      "fallback": "./assets/updates/2026-08-25/02-core-explanation-fallback.png?v=a13005bc73f0",
      "width": 768,
      "height": 768
    }
  },
  {
    "date": "2026-08-26",
    "type": "图文",
    "title": "AI 怎样辅助包装，但不能替代哪些判断",
    "time": "11:30",
    "summary": "进入 Day 4：涂装、包装、说明卡、拍摄和产品化表达。",
    "cover": "./assets/workshop-ai-launch.png",
    "published": false,
    "url": "",
    "status": "planned"
  },
  {
    "date": "2026-08-27",
    "type": "图文",
    "title": "一个产品说明卡必须写清的 8 项信息",
    "time": "11:30",
    "summary": "进入 Day 4：涂装、包装、说明卡、拍摄和产品化表达。",
    "cover": "./assets/workshop-hero-v2.png",
    "published": false,
    "url": "",
    "status": "planned"
  },
  {
    "date": "2026-08-28",
    "type": "视频",
    "title": "课程现场怎样拍出可用的过程与成品素材",
    "time": "19:30",
    "summary": "进入 Day 4：涂装、包装、说明卡、拍摄和产品化表达。",
    "cover": "./assets/workshop-modeling.png",
    "published": false,
    "url": "",
    "status": "planned"
  },
  {
    "date": "2026-08-29",
    "type": "视频",
    "title": "从灰模到包装：一件作品的产品化案例",
    "time": "18:00",
    "summary": "进入 Day 4：涂装、包装、说明卡、拍摄和产品化表达。",
    "cover": "./assets/workshop-printing-v2.png",
    "published": false,
    "url": "",
    "status": "planned"
  },
  {
    "date": "2026-08-30",
    "type": "直播",
    "title": "包装、版本和价格测试：作品怎样第一次面对市场",
    "time": "20:00",
    "summary": "进入 Day 4：涂装、包装、说明卡、拍摄和产品化表达。",
    "cover": "./assets/workshop-finishing.png",
    "published": false,
    "url": "",
    "status": "planned"
  },
  {
    "date": "2026-08-31",
    "type": "图文",
    "title": "Day 5 到底做什么：把五天成果变成个人数字阵地",
    "time": "11:30",
    "summary": "进入 Day 5：用 Codex 搭建个人独立站、发布 3D 展示，并用 AI 建立可持续的内容推广工作流。",
    "cover": "./assets/workshop-finishing.png",
    "published": false,
    "url": "",
    "status": "planned"
  },
  {
    "date": "2026-09-01",
    "type": "视频",
    "title": "Codex 怎样从零搭建个人独立站",
    "time": "19:30",
    "summary": "进入 Day 5：用 Codex 搭建个人独立站、发布 3D 展示，并用 AI 建立可持续的内容推广工作流。",
    "cover": "./assets/workshop-ai-launch.png",
    "published": false,
    "url": "",
    "status": "planned"
  },
  {
    "date": "2026-09-02",
    "type": "图文",
    "title": "GLB 怎样进入个人网页和在线 3D 展示",
    "time": "11:30",
    "summary": "进入 Day 5：用 Codex 搭建个人独立站、发布 3D 展示，并用 AI 建立可持续的内容推广工作流。",
    "cover": "./assets/workshop-hero-v2.png",
    "published": false,
    "url": "",
    "status": "planned"
  },
  {
    "date": "2026-09-03",
    "type": "视频",
    "title": "HERMES 怎样把项目资料变成持续发布内容",
    "time": "19:30",
    "summary": "进入 Day 5：用 Codex 搭建个人独立站、发布 3D 展示，并用 AI 建立可持续的内容推广工作流。",
    "cover": "./assets/workshop-modeling.png",
    "published": false,
    "url": "",
    "status": "planned"
  },
  {
    "date": "2026-09-04",
    "type": "视频",
    "title": "一套素材怎样适配朋友圈、小红书、抖音与 B 站",
    "time": "18:00",
    "summary": "进入 Day 5：用 Codex 搭建个人独立站、发布 3D 展示，并用 AI 建立可持续的内容推广工作流。",
    "cover": "./assets/workshop-printing-v2.png",
    "published": false,
    "url": "",
    "status": "planned"
  },
  {
    "date": "2026-09-05",
    "type": "图文",
    "title": "个人独立站需要准备的图片、模型和文字清单",
    "time": "11:30",
    "summary": "进入 Day 5：用 Codex 搭建个人独立站、发布 3D 展示，并用 AI 建立可持续的内容推广工作流。",
    "cover": "./assets/workshop-finishing.png",
    "published": false,
    "url": "",
    "status": "planned"
  },
  {
    "date": "2026-09-06",
    "type": "直播",
    "title": "从实体样品到个人独立站，现场做一遍",
    "time": "20:00",
    "summary": "进入 Day 5：用 Codex 搭建个人独立站、发布 3D 展示，并用 AI 建立可持续的内容推广工作流。",
    "cover": "./assets/workshop-ai-launch.png",
    "published": false,
    "url": "",
    "status": "planned"
  },
  {
    "date": "2026-09-07",
    "type": "图文",
    "title": "美术馆 / 画廊资源能提供什么，不能保证什么",
    "time": "11:30",
    "summary": "讲清成果展、授权、费用边界和最后一轮报名问题。",
    "cover": "./assets/workshop-ai-launch.png",
    "published": false,
    "url": "",
    "status": "planned"
  },
  {
    "date": "2026-09-08",
    "type": "视频",
    "title": "一份合格的成果展资料包包含什么",
    "time": "19:30",
    "summary": "讲清成果展、授权、费用边界和最后一轮报名问题。",
    "cover": "./assets/workshop-hero-v2.png",
    "published": false,
    "url": "",
    "status": "planned"
  },
  {
    "date": "2026-09-09",
    "type": "图文",
    "title": "做过模型，不等于自动拥有销售和授权权利",
    "time": "11:30",
    "summary": "讲清成果展、授权、费用边界和最后一轮报名问题。",
    "cover": "./assets/workshop-modeling.png",
    "published": false,
    "url": "",
    "status": "planned"
  },
  {
    "date": "2026-09-10",
    "type": "视频",
    "title": "完整五天日程、费用和包含边界最终版",
    "time": "19:30",
    "summary": "讲清成果展、授权、费用边界和最后一轮报名问题。",
    "cover": "./assets/workshop-printing-v2.png",
    "published": false,
    "url": "",
    "status": "planned"
  },
  {
    "date": "2026-09-11",
    "type": "图文",
    "title": "距离全款确认还有 9 天：你是否适合这门课",
    "time": "11:30",
    "summary": "讲清成果展、授权、费用边界和最后一轮报名问题。",
    "cover": "./assets/workshop-finishing.png",
    "published": false,
    "url": "",
    "status": "planned"
  },
  {
    "date": "2026-09-12",
    "type": "视频",
    "title": "候选项目拆解：它们分别会做到哪一级",
    "time": "18:00",
    "summary": "讲清成果展、授权、费用边界和最后一轮报名问题。",
    "cover": "./assets/workshop-ai-launch.png",
    "published": false,
    "url": "",
    "status": "planned"
  },
  {
    "date": "2026-09-13",
    "type": "直播",
    "title": "最后一次公开作品制作路径拆解",
    "time": "20:00",
    "summary": "讲清成果展、授权、费用边界和最后一轮报名问题。",
    "cover": "./assets/workshop-hero-v2.png",
    "published": false,
    "url": "",
    "status": "planned"
  },
  {
    "date": "2026-09-14",
    "type": "图文",
    "title": "距离全款确认还有 6 天：为什么本期必须小班",
    "time": "11:30",
    "summary": "进入最终确认：席位、设备、费用、合同、课前准备和正式名单。",
    "cover": "./assets/workshop-hero-v2.png",
    "published": false,
    "url": "",
    "status": "planned"
  },
  {
    "date": "2026-09-15",
    "type": "视频",
    "title": "报名学员设备检查：iPad、Nomad、电脑和网络",
    "time": "19:30",
    "summary": "进入最终确认：席位、设备、费用、合同、课前准备和正式名单。",
    "cover": "./assets/workshop-modeling.png",
    "published": false,
    "url": "",
    "status": "planned"
  },
  {
    "date": "2026-09-16",
    "type": "图文",
    "title": "学费包含什么、不包含什么：最终清单",
    "time": "11:30",
    "summary": "进入最终确认：席位、设备、费用、合同、课前准备和正式名单。",
    "cover": "./assets/workshop-printing-v2.png",
    "published": false,
    "url": "",
    "status": "planned"
  },
  {
    "date": "2026-09-17",
    "type": "图文",
    "title": "全款之后不是等待：你会立刻进入这 5 步",
    "time": "11:30",
    "summary": "进入最终确认：席位、设备、费用、合同、课前准备和正式名单。",
    "cover": "./assets/workshop-finishing.png",
    "published": false,
    "url": "",
    "status": "planned"
  },
  {
    "date": "2026-09-18",
    "type": "视频",
    "title": "全款确认前 48 小时：名额以实际确认表为准",
    "time": "19:30",
    "summary": "进入最终确认：席位、设备、费用、合同、课前准备和正式名单。",
    "cover": "./assets/workshop-ai-launch.png",
    "published": false,
    "url": "",
    "status": "planned"
  },
  {
    "date": "2026-09-19",
    "type": "直播",
    "title": "最终报名答疑：费用、设备、完成度、展览和退款",
    "time": "20:00",
    "summary": "进入最终确认：席位、设备、费用、合同、课前准备和正式名单。",
    "cover": "./assets/workshop-hero-v2.png",
    "published": false,
    "url": "",
    "status": "planned"
  },
  {
    "date": "2026-09-20",
    "type": "图文",
    "title": "正式名单确认日：感谢、候补与下一阶段",
    "time": "11:30",
    "summary": "进入最终确认：席位、设备、费用、合同、课前准备和正式名单。",
    "cover": "./assets/workshop-modeling.png",
    "published": false,
    "url": "",
    "status": "planned"
  },
  {
    "date": "2026-09-21",
    "type": "图文",
    "title": "绘画思维怎样替模型制作先做一次减法",
    "time": "11:30",
    "summary": "用明度、轮廓、边缘、色彩范围和主次，把复杂形象先压成六个可检查的制作判断。",
    "cover": "./assets/painting-thinking-to-object-v1.png",
    "published": false,
    "url": "",
    "status": "planned"
  },
  {
    "date": "2026-09-22",
    "type": "视频",
    "title": "三阶明度怎样决定模型的大中小体块",
    "time": "19:30",
    "summary": "在进入面部和服装细节前，先检查模型缩小和逆光时是否仍能读懂。",
    "cover": "./assets/painting-thinking-to-object-v1.png",
    "published": false,
    "url": "",
    "status": "planned"
  },
  {
    "date": "2026-09-23",
    "type": "图文",
    "title": "轮廓与负形：为什么侧面比正面更容易暴露问题",
    "time": "11:30",
    "summary": "用正面、侧面和四分之三视角检查姿态、重心、空隙和识别度。",
    "cover": "./assets/painting-thinking-to-object-v1.png",
    "published": false,
    "url": "",
    "status": "planned"
  },
  {
    "date": "2026-09-24",
    "type": "视频",
    "title": "硬边和软边怎样变成锐边、圆角与曲面",
    "time": "19:30",
    "summary": "把绘画里的边缘控制翻译为建模和修模动作，判断哪些地方应明确、哪些地方应连续。",
    "cover": "./assets/painting-thinking-to-object-v1.png",
    "published": false,
    "url": "",
    "status": "planned"
  },
  {
    "date": "2026-09-25",
    "type": "图文",
    "title": "先定限色色域，再开始涂模型",
    "time": "11:30",
    "summary": "用主色、辅色、强调色和综合色建立涂装系统，避免每个部位都独立选色。",
    "cover": "./assets/painting-thinking-to-object-v1.png",
    "published": false,
    "url": "",
    "status": "planned"
  },
  {
    "date": "2026-09-26",
    "type": "视频",
    "title": "细节预算：打印和手工时间应该花在哪里",
    "time": "18:00",
    "summary": "把焦点分为 A、支持区域分为 B、可降级区域分为 C，提前控制五天制作成本。",
    "cover": "./assets/painting-thinking-to-object-v1.png",
    "published": false,
    "url": "",
    "status": "planned"
  },
  {
    "date": "2026-09-27",
    "type": "直播",
    "title": "现场做一张原作视觉语法卡",
    "time": "20:00",
    "summary": "从一件二维作品现场提取三阶明度、轮廓、边缘、色彩范围、主次和不可丢失特征。",
    "cover": "./assets/painting-thinking-to-object-v1.png",
    "published": false,
    "url": "",
    "status": "planned"
  },
  {
    "date": "2026-09-28",
    "type": "图文",
    "title": "画层逻辑怎样变成模型涂装工序",
    "time": "11:30",
    "summary": "从底层、塑造、透明层和最终调整，安排底漆、铺色、罩色、旧化与保护层。",
    "cover": "./assets/painting-thinking-to-object-v1.png",
    "published": false,
    "url": "",
    "status": "planned"
  },
  {
    "date": "2026-09-29",
    "type": "视频",
    "title": "同一件作品的完整、半身、浮雕和数字四种出口",
    "time": "19:30",
    "summary": "项目降级不是失败，而是根据识别度、结构、工艺和五天产能选择可交付结果。",
    "cover": "./assets/painting-thinking-to-object-v1.png",
    "published": false,
    "url": "",
    "status": "planned"
  },
  {
    "date": "2026-09-30",
    "type": "图文",
    "title": "五天课的六张表：从判断到可复现",
    "time": "11:30",
    "summary": "公开项目卡、视觉语法卡、结构检查、限色色板、材料护照和细节预算的使用方法。",
    "cover": "./assets/painting-thinking-to-object-v1.png",
    "published": false,
    "url": "",
    "status": "planned"
  },
  {
    "date": "2026-10-01",
    "type": "视频",
    "title": "开课前最后检查：资料、设备、权利和最低成果",
    "time": "18:00",
    "summary": "逐项确认项目主备方案、文件夹、设备、材料、安全、版权和五天最低交付。",
    "cover": "./assets/painting-thinking-to-object-v1.png",
    "published": false,
    "url": "",
    "status": "planned"
  }
];
